/*
SQLyog Community
MySQL - 8.0.31 : Database - tmp2
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `sma_district` */

CREATE TABLE `sma_district` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `priority` int DEFAULT '100',
  `parent_id` int DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=560 DEFAULT CHARSET=utf8mb3;

/*Data for the table `sma_district` */

insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (1,'কক্সবাজার',1,1,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (2,'কিশোরগঞ্জ',1,2,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (3,'কুড়িগ্রাম',1,3,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (4,'কুষ্টিয়া',1,4,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (5,'খাগড়াছড়ি',1,5,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (6,'খুলনা',1,6,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (7,'গাইবান্ধা',1,7,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (8,'গাজীপুর',1,8,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (9,'গোপালগঞ্জ',1,9,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (10,'চট্টগ্রাম',1,10,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (11,'চাঁদপুর',1,11,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (12,'চাঁপাইনবাবগঞ্জ',1,12,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (13,'চুয়াডাঙ্গা',1,13,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (14,'জয়পুরহাট',1,14,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (15,'জামালপুর',1,15,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (16,'ঝিনাইদহ',1,16,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (17,'টাঙ্গাইল',1,17,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (18,'ঠাকুরগাঁও',1,18,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (19,'ঢাকা',1,19,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (20,'দিনাজপুর',1,20,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (21,'নওগাঁ',1,21,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (22,'নড়াইল',1,22,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (23,'নাটোর',1,23,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (24,'নারায়ণগঞ্জ',1,24,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (25,'নীলফামারী',1,25,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (26,'নেত্রকোণা',1,26,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (27,'নোয়াখালী',1,27,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (28,'পটুয়াখালী',1,28,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (29,'পাবনা',1,29,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (30,'পিরোজপুর',1,30,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (31,'ফরিদপুর',1,31,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (32,'ফেনী',1,32,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (33,'বগুড়া',1,33,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (34,'বরগুনা',1,34,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (35,'বরিশাল',1,35,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (36,'বাগেরহাট',1,36,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (37,'বান্দরবান',1,37,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (38,'ব্রাহ্মণবাড়িয়া',1,38,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (39,'ভোলা',1,39,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (40,'ময়মনসিংহ',1,40,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (41,'মাগুরা',1,41,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (42,'মাদারীপুর',1,42,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (43,'মানিকগঞ্জ',1,43,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (44,'মুন্সিগঞ্জ',1,44,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (45,'মেহেরপুর',1,45,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (46,'মৌলভীবাজার',1,46,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (47,'রংপুর',1,47,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (48,'রাঙ্গামাটি',1,48,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (49,'রাজবাড়ী',1,49,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (50,'রাজশাহী',1,50,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (51,'লক্ষ্মীপুর',1,51,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (52,'লালমনিরহাট',1,52,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (53,'শরীয়তপুর',1,53,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (54,'সাতক্ষীরা',1,54,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (55,'সুনামগঞ্জ',1,55,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (56,'হবিগঞ্জ',1,56,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (57,'কুমিল্লা',1,57,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (58,'ঝালকাঠি',1,58,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (59,'নরসিংদী',1,59,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (60,'পঞ্চগড়',1,60,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (61,'যশোর',1,61,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (62,'শেরপুর',1,62,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (63,'সিরাজগঞ্জ',1,63,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (64,'সিলেট',1,64,0);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (66,'দেবিদ্বার',1,100,57);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (67,'বরুড়া',1,100,57);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (68,'ব্রাহ্মণপাড়া',1,100,57);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (69,'চান্দিনা',1,100,57);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (70,'চৌদ্দগ্রাম',1,100,57);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (71,'দাউদকান্দি',1,100,57);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (72,'হোমনা',1,100,57);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (73,'লাকসাম',1,100,57);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (74,'মুরাদনগর',1,100,57);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (75,'নাঙ্গলকোট',1,100,57);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (76,'কুমিল্লা সদর',1,100,57);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (77,'মেঘনা',1,100,57);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (78,'মনোহরগঞ্জ',1,100,57);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (79,'সদর দক্ষিণ',1,100,57);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (80,'তিতাস',1,100,57);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (81,'বুড়িচং',1,100,57);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (82,'লালমাই',1,100,57);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (83,'ছাগলনাইয়া',1,100,32);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (84,'ফেনী সদর',1,100,32);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (85,'সোনাগাজী',1,100,32);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (86,'ফুলগাজী',1,100,32);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (87,'পরশুরাম',1,100,32);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (88,'দাগনভূঞা',1,100,32);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (89,'ব্রাহ্মণবাড়িয়া সদর',1,100,38);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (90,'কসবা',1,100,38);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (91,'নাসিরনগর',1,100,38);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (92,'সরাইল',1,100,38);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (93,'আশুগঞ্জ',1,100,38);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (94,'আখাউড়া',1,100,38);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (95,'নবীনগর',1,100,38);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (96,'বাঞ্ছারামপুর',1,100,38);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (97,'বিজয়নগর',1,100,38);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (98,'রাঙ্গামাটি সদর',1,100,48);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (99,'কাপ্তাই',1,100,48);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (100,'কাউখালী',1,100,48);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (101,'বাঘাইছড়ি',1,100,48);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (102,'বরকল',1,100,48);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (103,'লংগদু',1,100,48);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (104,'রাজস্থলী',1,100,48);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (105,'বিলাইছড়ি',1,100,48);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (106,'জুরাছড়ি',1,100,48);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (107,'নানিয়ারচর',1,100,48);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (108,'নোয়াখালী সদর',1,100,27);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (109,'কোম্পানীগঞ্জ',1,100,27);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (110,'বেগমগঞ্জ',1,100,27);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (111,'হাতিয়া',1,100,27);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (112,'সুবর্ণচর',1,100,27);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (113,'কবিরহাট',1,100,27);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (114,'সেনবাগ',1,100,27);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (115,'চাটখিল',1,100,27);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (116,'সোনাইমুড়ী',1,100,27);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (117,'হাইমচর',1,100,11);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (118,'কচুয়া',1,100,11);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (119,'শাহরাস্তি	',1,100,11);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (120,'চাঁদপুর সদর',1,100,11);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (121,'মতলব দক্ষিণ',1,100,11);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (122,'হাজীগঞ্জ',1,100,11);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (123,'মতলব উত্তর',1,100,11);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (124,'ফরিদগঞ্জ',1,100,11);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (125,'লক্ষ্মীপুর সদর',1,100,51);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (126,'কমলনগর',1,100,51);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (127,'রায়পুর',1,100,51);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (128,'রামগতি',1,100,51);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (129,'রামগঞ্জ',1,100,51);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (130,'রাঙ্গুনিয়া',1,100,10);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (131,'সীতাকুন্ড',1,100,10);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (132,'মীরসরাই',1,100,10);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (133,'পটিয়া',1,100,10);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (134,'সন্দ্বীপ',1,100,10);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (135,'বাঁশখালী',1,100,10);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (136,'বোয়ালখালী',1,100,10);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (137,'আনোয়ারা',1,100,10);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (138,'চন্দনাইশ',1,100,10);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (139,'সাতকানিয়া',1,100,10);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (140,'লোহাগাড়া',1,100,10);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (141,'হাটহাজারী',1,100,10);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (142,'ফটিকছড়ি',1,100,10);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (143,'রাউজান',1,100,10);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (144,'কর্ণফুলী',1,100,10);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (145,'কক্সবাজার সদর',1,100,1);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (146,'চকরিয়া',1,100,1);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (147,'কুতুবদিয়া',1,100,1);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (148,'উখিয়া',1,100,1);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (149,'মহেশখালী',1,100,1);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (150,'পেকুয়া',1,100,1);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (151,'রামু',1,100,1);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (152,'টেকনাফ',1,100,1);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (153,'খাগড়াছড়ি সদর',1,100,5);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (154,'দিঘীনালা',1,100,5);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (155,'পানছড়ি',1,100,5);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (156,'লক্ষীছড়ি',1,100,5);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (157,'মহালছড়ি',1,100,5);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (158,'মানিকছড়ি',1,100,5);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (159,'রামগড়',1,100,5);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (160,'মাটিরাঙ্গা',1,100,5);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (161,'গুইমারা',1,100,5);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (162,'বান্দরবান সদর',1,100,37);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (163,'আলীকদম',1,100,37);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (164,'নাইক্ষ্যংছড়ি',1,100,37);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (165,'রোয়াংছড়ি',1,100,37);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (166,'লামা',1,100,37);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (167,'রুমা',1,100,37);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (168,'থানচি',1,100,37);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (169,'বেলকুচি',1,100,63);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (170,'চৌহালি',1,100,63);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (171,'কামারখন্দ',1,100,63);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (172,'কাজীপুর',1,100,63);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (173,'রায়গঞ্জ',1,100,63);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (174,'শাহজাদপুর',1,100,63);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (175,'সিরাজগঞ্জ সদর',1,100,63);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (176,'তাড়াশ',1,100,63);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (177,'উল্লাপাড়া',1,100,63);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (178,'সুজানগর',1,100,29);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (179,'ঈশ্বরদী',1,100,29);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (180,'ভাঙ্গুড়া',1,100,29);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (181,'পাবনা সদর',1,100,29);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (182,'বেড়া',1,100,29);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (183,'আটঘরিয়া',1,100,29);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (184,'চাটমোহর',1,100,29);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (185,'সাঁথিয়া',1,100,29);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (186,'ফরিদপুর',1,100,29);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (187,'কাহালু',1,100,33);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (188,'বগুড়া সদর',1,100,33);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (189,'সারিয়াকান্দি',1,100,33);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (190,'শাজাহানপুর',1,100,33);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (191,'দুপচাচিঁয়া',1,100,33);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (192,'আদমদিঘি',1,100,33);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (193,'নন্দিগ্রাম',1,100,33);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (194,'সোনাতলা',1,100,33);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (195,'ধুনট',1,100,33);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (196,'গাবতলী',1,100,33);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (197,'শেরপুর',1,100,33);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (198,'শিবগঞ্জ',1,100,33);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (199,'পবা',1,100,50);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (200,'দুর্গাপুর',1,100,50);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (201,'মোহনপুর',1,100,50);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (202,'চারঘাট',1,100,50);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (203,'পুঠিয়া',1,100,50);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (204,'বাঘা',1,100,50);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (205,'গোদাগাড়ী',1,100,50);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (206,'তানোর',1,100,50);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (207,'বাগমারা',1,100,50);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (208,'নাটোর সদর',1,100,23);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (209,'সিংড়া',1,100,23);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (210,'বড়াইগ্রাম',1,100,23);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (211,'বাগাতিপাড়া',1,100,23);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (212,'লালপুর',1,100,23);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (213,'গুরুদাসপুর',1,100,23);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (214,'নলডাঙ্গা',1,100,23);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (215,'আক্কেলপুর',1,100,14);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (216,'কালাই',1,100,14);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (217,'ক্ষেতলাল',1,100,14);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (218,'পাঁচবিবি',1,100,14);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (219,'জয়পুরহাট সদর',1,100,14);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (220,'চাঁপাইনবাবগঞ্জ সদর',1,100,12);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (221,'গোমস্তাপুর',1,100,12);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (222,'নাচোল',1,100,12);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (223,'ভোলাহাট',1,100,12);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (224,'শিবগঞ্জ',1,100,12);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (225,'মহাদেবপুর',1,100,21);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (226,'বদলগাছী',1,100,21);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (227,'পত্নিতলা',1,100,21);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (228,'ধামইরহাট',1,100,21);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (229,'নিয়ামতপুর',1,100,21);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (230,'মান্দা',1,100,21);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (231,'আত্রাই',1,100,21);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (232,'রাণীনগর',1,100,21);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (233,'নওগাঁ সদর',1,100,21);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (234,'পোরশা',1,100,21);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (235,'সাপাহার',1,100,21);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (236,'মণিরামপুর',1,100,61);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (237,'অভয়নগর',1,100,61);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (238,'বাঘারপাড়া',1,100,61);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (239,'চৌগাছা',1,100,61);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (240,'ঝিকরগাছা',1,100,61);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (241,'কেশবপুর',1,100,61);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (242,'যশোর সদর',1,100,61);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (243,'শার্শা',1,100,61);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (244,'আশাশুনি',1,100,54);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (245,'দেবহাটা',1,100,54);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (246,'কলারোয়া',1,100,54);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (247,'সাতক্ষীরা সদর',1,100,54);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (248,'শ্যামনগর',1,100,54);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (249,'তালা',1,100,54);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (250,'কালিগঞ্জ',1,100,54);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (251,'মুজিবনগর',1,100,45);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (252,'মেহেরপুর সদর',1,100,45);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (253,'গাংনী',1,100,45);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (254,'নড়াইল সদর',1,100,22);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (255,'লোহাগড়া',1,100,22);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (256,'কালিয়া',1,100,22);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (257,'চুয়াডাঙ্গা সদর',1,100,13);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (258,'আলমডাঙ্গা',1,100,13);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (259,'দামুড়হুদা',1,100,13);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (260,'জীবননগর',1,100,13);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (261,'কুষ্টিয়া সদর',1,100,4);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (262,'কুমারখালী',1,100,4);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (263,'খোকসা',1,100,4);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (264,'মিরপুর',1,100,4);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (265,'দৌলতপুর',1,100,4);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (266,'ভেড়ামারা',1,100,4);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (267,'শালিখা',1,100,41);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (268,'শ্রীপুর',1,100,41);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (269,'মাগুরা সদর',1,100,41);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (270,'মহম্মদপুর',1,100,41);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (271,'পাইকগাছা',1,100,6);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (272,'ফুলতলা',1,100,6);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (273,'দিঘলিয়া',1,100,6);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (274,'রূপসা',1,100,6);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (275,'তেরখাদা',1,100,6);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (276,'ডুমুরিয়া',1,100,6);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (277,'বটিয়াঘাটা',1,100,6);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (278,'দাকোপ',1,100,6);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (279,'কয়রা',1,100,6);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (280,'ফকিরহাট',1,100,36);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (281,'বাগেরহাট সদর',1,100,36);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (282,'মোল্লাহাট',1,100,36);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (283,'শরণখোলা',1,100,36);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (284,'রামপাল',1,100,36);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (285,'মোড়েলগঞ্জ',1,100,36);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (286,'কচুয়া',1,100,36);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (287,'মোংলা',1,100,36);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (288,'চিতলমারী',1,100,36);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (289,'ঝিনাইদহ সদর',1,100,16);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (290,'শৈলকুপা',1,100,16);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (291,'হরিণাকুন্ডু',1,100,16);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (292,'কালীগঞ্জ',1,100,16);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (293,'কোটচাঁদপুর',1,100,16);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (294,'মহেশপুর',1,100,16);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (295,'ঝালকাঠি সদর',1,100,58);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (296,'কাঠালিয়া',1,100,58);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (297,'নলছিটি',1,100,58);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (298,'রাজাপুর',1,100,58);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (299,'বাউফল',1,100,28);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (300,'পটুয়াখালী সদর',1,100,28);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (301,'দুমকি',1,100,28);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (302,'দশমিনা',1,100,28);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (303,'কলাপাড়া',1,100,28);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (304,'মির্জাগঞ্জ',1,100,28);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (305,'গলাচিপা',1,100,28);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (306,'রাঙ্গাবালী',1,100,28);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (307,'পিরোজপুর সদর',1,100,30);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (308,'নাজিরপুর',1,100,30);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (309,'কাউখালী',1,100,30);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (310,'জিয়ানগর',1,100,30);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (311,'ভান্ডারিয়া',1,100,30);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (312,'মঠবাড়ীয়া',1,100,30);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (313,'নেছারাবাদ',1,100,30);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (314,'বরিশাল সদর',1,100,35);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (315,'বাকেরগঞ্জ',1,100,35);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (316,'বাবুগঞ্জ',1,100,35);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (317,'উজিরপুর',1,100,35);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (318,'বানারীপাড়া',1,100,35);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (319,'গৌরনদী',1,100,35);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (320,'আগৈলঝাড়া',1,100,35);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (321,'মেহেন্দিগঞ্জ',1,100,35);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (322,'মুলাদী',1,100,35);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (323,'হিজলা',1,100,35);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (324,'ভোলা সদর',1,100,39);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (325,'বোরহান উদ্দিন',1,100,39);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (326,'চরফ্যাশন',1,100,39);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (327,'দৌলতখান',1,100,39);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (328,'মনপুরা',1,100,39);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (329,'তজুমদ্দিন',1,100,39);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (330,'লালমোহন',1,100,39);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (331,'আমতলী',1,100,34);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (332,'বরগুনা সদর',1,100,34);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (333,'বেতাগী',1,100,34);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (334,'বামনা',1,100,34);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (335,'পাথরঘাটা',1,100,34);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (336,'তালতলি',1,100,34);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (337,'বালাগঞ্জ',1,100,64);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (338,'বিয়ানীবাজার',1,100,64);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (339,'বিশ্বনাথ',1,100,64);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (340,'কোম্পানীগঞ্জ',1,100,64);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (341,'ফেঞ্চুগঞ্জ',1,100,64);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (342,'গোলাপগঞ্জ',1,100,64);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (343,'গোয়াইনঘাট',1,100,64);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (344,'জৈন্তাপুর',1,100,64);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (345,'কানাইঘাট',1,100,64);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (346,'সিলেট সদর',1,100,64);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (347,'জকিগঞ্জ',1,100,64);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (348,'দক্ষিণ সুরমা',1,100,64);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (349,'ওসমানী নগর',1,100,64);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (350,'বড়লেখা',1,100,46);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (351,'কমলগঞ্জ',1,100,46);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (352,'কুলাউড়া',1,100,46);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (353,'মৌলভীবাজার সদর',1,100,46);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (354,'রাজনগর',1,100,46);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (355,'শ্রীমঙ্গল',1,100,46);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (356,'জুড়ী',1,100,46);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (357,'নবীগঞ্জ',1,100,56);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (358,'বাহুবল',1,100,56);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (359,'আজমিরীগঞ্জ',1,100,56);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (360,'বানিয়াচং',1,100,56);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (361,'লাখাই',1,100,56);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (362,'চুনারুঘাট',1,100,56);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (363,'হবিগঞ্জ সদর',1,100,56);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (364,'মাধবপুর',1,100,56);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (365,'সুনামগঞ্জ সদর',1,100,55);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (366,'দক্ষিণ সুনামগঞ্জ',1,100,55);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (367,'বিশ্বম্ভরপুর',1,100,55);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (368,'ছাতক',1,100,55);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (369,'জগন্নাথপুর',1,100,55);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (370,'দোয়ারাবাজার',1,100,55);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (371,'তাহিরপুর',1,100,55);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (372,'ধর্মপাশা',1,100,55);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (373,'জামালগঞ্জ',1,100,55);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (374,'শাল্লা',1,100,55);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (375,'দিরাই',1,100,55);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (376,'বেলাবো',1,100,59);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (377,'মনোহরদী',1,100,59);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (378,'নরসিংদী সদর',1,100,59);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (379,'পলাশ',1,100,59);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (380,'রায়পুরা',1,100,59);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (381,'শিবপুর',1,100,59);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (382,'কালীগঞ্জ',1,100,8);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (383,'কালিয়াকৈর',1,100,8);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (384,'কাপাসিয়া',1,100,8);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (385,'গাজীপুর সদর',1,100,8);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (386,'শ্রীপুর',1,100,8);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (387,'শরিয়তপুর সদর',1,100,53);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (388,'নড়িয়া',1,100,53);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (389,'জাজিরা',1,100,53);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (390,'গোসাইরহাট',1,100,53);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (391,'ভেদরগঞ্জ',1,100,53);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (392,'ডামুড্যা',1,100,53);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (393,'আড়াইহাজার',1,100,24);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (394,'বন্দর',1,100,24);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (395,'নারায়নগঞ্জ সদর',1,100,24);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (396,'রূপগঞ্জ',1,100,24);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (397,'সোনারগাঁ',1,100,24);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (398,'বাসাইল',1,100,17);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (399,'ভুয়াপুর',1,100,17);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (400,'দেলদুয়ার',1,100,17);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (401,'ঘাটাইল',1,100,17);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (402,'গোপালপুর',1,100,17);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (403,'মধুপুর',1,100,17);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (404,'মির্জাপুর',1,100,17);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (405,'নাগরপুর',1,100,17);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (406,'সখিপুর',1,100,17);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (407,'টাঙ্গাইল সদর',1,100,17);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (408,'কালিহাতী',1,100,17);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (409,'ধনবাড়ী',1,100,17);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (410,'ইটনা',1,100,2);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (411,'কটিয়াদী',1,100,2);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (412,'ভৈরব',1,100,2);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (413,'তাড়াইল',1,100,2);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (414,'হোসেনপুর',1,100,2);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (415,'পাকুন্দিয়া',1,100,2);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (416,'কুলিয়ারচর',1,100,2);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (417,'কিশোরগঞ্জ সদর',1,100,2);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (418,'করিমগঞ্জ',1,100,2);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (419,'বাজিতপুর',1,100,2);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (420,'অষ্টগ্রাম',1,100,2);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (421,'মিঠামইন',1,100,2);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (422,'নিকলী',1,100,2);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (423,'হরিরামপুর',1,100,43);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (424,'সাটুরিয়া',1,100,43);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (425,'মানিকগঞ্জ সদর',1,100,43);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (426,'ঘিওর',1,100,43);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (427,'শিবালয়',1,100,43);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (428,'দৌলতপুর',1,100,43);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (429,'সিংগাইর',1,100,43);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (430,'সাভার',1,100,19);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (431,'ধামরাই',1,100,19);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (432,'কেরাণীগঞ্জ',1,100,19);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (433,'নবাবগঞ্জ',1,100,19);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (434,'দোহার',1,100,19);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (435,'মুন্সিগঞ্জ সদর',1,100,44);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (436,'শ্রীনগর',1,100,44);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (437,'সিরাজদিখান',1,100,44);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (438,'লৌহজং',1,100,44);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (439,'গজারিয়া',1,100,44);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (440,'টংগীবাড়ি',1,100,44);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (441,'রাজবাড়ী সদর',1,100,49);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (442,'গোয়ালন্দ',1,100,49);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (443,'পাংশা',1,100,49);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (444,'বালিয়াকান্দি',1,100,49);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (445,'কালুখালী',1,100,49);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (446,'মাদারীপুর সদর',1,100,42);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (447,'শিবচর',1,100,42);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (448,'কালকিনি',1,100,42);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (449,'রাজৈর',1,100,42);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (450,'গোপালগঞ্জ সদর',1,100,9);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (451,'কাশিয়ানী',1,100,9);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (452,'টুংগীপাড়া',1,100,9);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (453,'কোটালীপাড়া',1,100,9);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (454,'মুকসুদপুর',1,100,9);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (455,'ফরিদপুর সদর',1,100,31);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (456,'আলফাডাঙ্গা',1,100,31);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (457,'বোয়ালমারী',1,100,31);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (458,'সদরপুর',1,100,31);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (459,'নগরকান্দা',1,100,31);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (460,'ভাঙ্গা',1,100,31);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (461,'চরভদ্রাসন',1,100,31);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (462,'মধুখালী',1,100,31);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (463,'সালথা',1,100,31);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (464,'পঞ্চগড় সদর',1,100,60);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (465,'দেবীগঞ্জ',1,100,60);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (466,'বোদা',1,100,60);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (467,'আটোয়ারী',1,100,60);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (468,'তেতুলিয়া',1,100,60);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (469,'নবাবগঞ্জ',1,100,20);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (470,'বীরগঞ্জ',1,100,20);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (471,'ঘোড়াঘাট',1,100,20);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (472,'বিরামপুর',1,100,20);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (473,'পার্বতীপুর',1,100,20);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (474,'বোচাগঞ্জ',1,100,20);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (475,'কাহারোল',1,100,20);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (476,'ফুলবাড়ী',1,100,20);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (477,'দিনাজপুর সদর',1,100,20);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (478,'হাকিমপুর',1,100,20);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (479,'খানসামা',1,100,20);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (480,'বিরল',1,100,20);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (481,'চিরিরবন্দর',1,100,20);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (482,'লালমনিরহাট সদর',1,100,52);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (483,'কালীগঞ্জ',1,100,52);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (484,'হাতীবান্ধা',1,100,52);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (485,'পাটগ্রাম',1,100,52);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (486,'আদিতমারী',1,100,52);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (487,'সৈয়দপুর',1,100,25);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (488,'ডোমার',1,100,25);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (489,'ডিমলা',1,100,25);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (490,'জলঢাকা',1,100,25);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (491,'কিশোরগঞ্জ',1,100,25);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (492,'নীলফামারী সদর',1,100,25);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (493,'সাদুল্লাপুর',1,100,7);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (494,'গাইবান্ধা সদর',1,100,7);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (495,'পলাশবাড়ী',1,100,7);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (496,'সাঘাটা',1,100,7);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (497,'গোবিন্দগঞ্জ',1,100,7);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (498,'সুন্দরগঞ্জ',1,100,7);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (499,'ফুলছড়ি',1,100,7);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (500,'ঠাকুরগাঁও সদর',1,100,18);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (501,'পীরগঞ্জ',1,100,18);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (502,'রাণীশংকৈল',1,100,18);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (503,'হরিপুর',1,100,18);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (504,'বালিয়াডাঙ্গী',1,100,18);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (505,'রংপুর সদর',1,100,47);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (506,'গংগাচড়া',1,100,47);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (507,'তারাগঞ্জ',1,100,47);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (508,'বদরগঞ্জ',1,100,47);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (509,'মিঠাপুকুর',1,100,47);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (510,'পীরগঞ্জ',1,100,47);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (511,'কাউনিয়া',1,100,47);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (512,'পীরগাছা',1,100,47);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (513,'কুড়িগ্রাম সদর',1,100,3);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (514,'নাগেশ্বরী',1,100,3);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (515,'ভুরুঙ্গামারী',1,100,3);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (516,'ফুলবাড়ী',1,100,3);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (517,'রাজারহাট',1,100,3);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (518,'উলিপুর',1,100,3);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (519,'চিলমারী',1,100,3);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (520,'রৌমারী',1,100,3);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (521,'চর রাজিবপুর',1,100,3);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (522,'শেরপুর সদর',1,100,62);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (523,'নালিতাবাড়ী',1,100,62);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (524,'শ্রীবরদী',1,100,62);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (525,'নকলা',1,100,62);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (526,'ঝিনাইগাতী',1,100,62);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (527,'ফুলবাড়ীয়া',1,100,40);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (528,'ত্রিশাল',1,100,40);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (529,'ভালুকা',1,100,40);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (530,'মুক্তাগাছা',1,100,40);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (531,'ময়মনসিংহ সদর',1,100,40);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (532,'ধোবাউড়া',1,100,40);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (533,'ফুলপুর',1,100,40);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (534,'হালুয়াঘাট',1,100,40);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (535,'গৌরীপুর',1,100,40);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (536,'গফরগাঁও',1,100,40);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (537,'ঈশ্বরগঞ্জ',1,100,40);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (538,'নান্দাইল',1,100,40);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (539,'তারাকান্দা',1,100,40);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (540,'জামালপুর সদর',1,100,15);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (541,'মেলান্দহ',1,100,15);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (542,'ইসলামপুর',1,100,15);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (543,'দেওয়ানগঞ্জ',1,100,15);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (544,'সরিষাবাড়ী',1,100,15);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (545,'মাদারগঞ্জ',1,100,15);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (546,'বকশীগঞ্জ',1,100,15);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (547,'বারহাট্টা',1,100,26);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (548,'দুর্গাপুর',1,100,26);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (549,'কেন্দুয়া',1,100,26);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (550,'আটপাড়া',1,100,26);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (551,'মদন',1,100,26);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (552,'খালিয়াজুরী',1,100,26);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (553,'কলমাকান্দা',1,100,26);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (554,'মোহনগঞ্জ',1,100,26);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (555,'পূর্বধলা',1,100,26);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (556,'নেত্রকোণা সদর',1,100,26);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (557,'ঈদগাঁও',1,100,1);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (558,'মধ্যনগর',1,100,55);
insert  into `sma_district`(`id`,`name`,`is_active`,`priority`,`parent_id`) values (559,'ডাসার',1,100,42);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
